services:
  web:
    # versión
    image: nginx:latest
    # Puerto 443 
    ports:
      - "443:443"  # Cambiar de 80 a 443 para HTTPS
    volumes:
      - ./build:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl  # Monta la carpeta SSL
