version: '3.8'
services:
  laravel-app:
    image: laravel:latest
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - backend
    expose:
      - "9000"

  nginx-server:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"   # Puerto HTTP
      - "443:443" # Puerto HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - laravel-app
    networks:
      - backend

networks:
  backend:
    driver: bridge
