version: '3.7'

services:
  # Contenedor para PHP-FPM (Laravel)
  app:
    image: php:8.1-fpm
    container_name: laravel-app
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-net
    # La configuración de la base de datos se define en el archivo .env de Laravel

  # Contenedor de Nginx con configuración SSL
  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx:/etc/nginx/certs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
      - "80:80"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
